#This is a basic workflow to help you get started with Actions

gi
name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install packages
        run: npm install --only=prod

      - name: Inject env variables
        run: |
          touch .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env

      - name: Run the React.js build script
        run: npm run build
        
      - name: Archive built files
        uses: actions/upload-artifact@master
        with:
          name: react-build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: react-build
          path: build

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install gh-pages
        run: |
          npm install gh-pages
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.name "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          